# This is the network config written by 'subiquity'
network:
  ethernets:
    enp0s3:
      dhcp4: false
      addresses: [10.0.2.4/24]
      gateway4: 10.0.2.1
      nameservers:
        addresses: [10.0.2.1]
  version: 2
