var student = { name: "Tom", age: 18};
var name = "hello world from var";
console.log(typeof name);
console.log(name);
var i = 0;
i++;
console.log("i =",i);
var arr = "1:2:3:4".split(":");
console.log(arr);
arr_dup = arr;
arr_dup = arr_dup.toString();
console.log(arr_dup);
arr = arr.join(":");
console.log(arr);
var arr1 = [];
arr1.pop();
console.log(arr1);
