# Generated by Django 3.1.5 on 2021-01-14 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookinfo',
            old_name='bpub_date',
            new_name='bPub_date',
        ),
        migrations.RenameField(
            model_name='bookinfo',
            old_name='btitle',
            new_name='bTitle',
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hName', models.CharField(max_length=20)),
                ('hGender', models.BooleanField(default=False)),
                ('hComment', models.CharField(max_length=128)),
                ('hBook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booktest.bookinfo')),
            ],
        ),
    ]
